/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Presentacion.*;
import Entidad.Usuario;
import Negocio.conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Presentacion.frm_Admin;
import Presentacion.frm_empleado;

/**
 *
 * @author bryan
 */
public class frm_Login extends javax.swing.JFrame {

    public static String   user = "";
    String pass ;
    /**
     * Creates new form frm_Login
     */
    public frm_Login() {
        initComponents();
        
        setResizable(false);//evita que el usuario cambie el tamaño de nuestra interfaz
        setTitle("Acceso a Sistema");//cambiar el titulo 
        setLocationRelativeTo(null);//indicar al programa para que centre la interfaz 
    }

     //cambiar la imagen del logo de la taza 
    //Inicio
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    } //Fin
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_user = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton_Acceder = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 140, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 110, 20));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 180, 30));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 180, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 160, 50));

        jButton_Acceder.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Acceder.setText("ACCEDER");
        jButton_Acceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_AccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_AccederMouseExited(evt);
            }
        });
        jButton_Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AccederActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 160, 50));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon("E:\\2021-II\\lp3\\u2\\proyec\\TooQTooQ\\src\\imagenes\\1234556.jpg")); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AccederActionPerformed
       
        user = txt_user.getText().trim();//obtenemos los valores y el metodo trim nos ayuda a eliminar los espacios al extremo
        pass = txt_password.getText().trim();
        //Enviamos los datos  a la clase
        Usuario usuario = new Usuario();
        usuario.setUsernameUsuario(user);
        usuario.setContrasenaUsuario(pass);
        if (!user.equals("") || !pass.equals("")) {
            try {
                Connection cn = conexion.Conectar();
                PreparedStatement pst = cn.prepareStatement("select tipoNivel from usuario where username = '" + user
                        + "' and contraseña = '" + pass + "'");
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    //recuperamos los valores de tipodeNivel 
                    String tipoNivel = rs.getString("tipoNivel");

                    if (tipoNivel.equalsIgnoreCase("Administrador")) {
                        dispose();
                        new frm_Admin().setVisible(true);
                    } else if (tipoNivel.equalsIgnoreCase("Mesero")) {
                        dispose();
                        new frm_empleado().setVisible(true);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos");
                    txt_user.setText("");
                    txt_password.setText("");
                }

            } catch (SQLException e) {
                System.err.println("Error en el boton Acceder." + e);
                JOptionPane.showMessageDialog(null, "Ocurrio un error contacte con el Administrador");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Datos Incorrectos");
            txt_user.setText("");
            txt_password.setText("");
        }

    }//GEN-LAST:event_jButton_AccederActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_user.setText("");
        txt_password.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_AccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AccederMouseEntered
        // TODO add your handling code here:
        jButton_Acceder.setBackground(Color.green);
    }//GEN-LAST:event_jButton_AccederMouseEntered

    private void jButton_AccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AccederMouseExited
        // TODO add your handling code here:
        jButton_Acceder.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButton_AccederMouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(Color.red);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Acceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
