/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.Boleta;
import Entidad.Facturacompras;
import Entidad.Proveedor;
import Negocio.BD_REPORTES;
import Negocio.bd_Conexion;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author vicra
 */
public class frm_factcompras extends javax.swing.JFrame {

    /**
     * Creates new form frm_factcompras
     */
    public frm_factcompras() {
        initComponents();       
        
        setResizable(false);
        setTitle("Facturas compras");
        setLocationRelativeTo(null);
        //para evitar que el programa finalice al cerrar la interfaz de registro de usuario
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_razon = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        generarFactura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_fecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        factura = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        generarFactura1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_direc = new javax.swing.JTextField();
        txt_ruc = new javax.swing.JTextField();
        txt_telf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(11, 156, 228));
        jPanel1.setForeground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Razon social");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel15.setText("RUC:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel16.setText("Direccion");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel17.setText("Telefono:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txt_razon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_razon.setEnabled(false);
        txt_razon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_razonActionPerformed(evt);
            }
        });
        txt_razon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_razonKeyTyped(evt);
            }
        });
        jPanel1.add(txt_razon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 200, 20));

        txt_total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_totalKeyTyped(evt);
            }
        });
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 60, 30));

        generarFactura.setIcon(new javax.swing.ImageIcon("E:\\2021-II\\lp3\\u2\\proyec\\TooQTooQ\\src\\imagenes\\buscar.png")); // NOI18N
        generarFactura.setText("Buscar");
        generarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generarFacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generarFacturaMouseExited(evt);
            }
        });
        generarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(generarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, 30));

        jLabel4.setText("MONTO TOTAL   :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));
        jPanel1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 200, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Restaurant");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Yoto's");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        factura.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        factura.setText("FACTURA COMPRAS");
        jPanel1.add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel13.setText("ID Prov.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_bus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busKeyTyped(evt);
            }
        });
        jPanel1.add(txt_bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, 30));

        generarFactura1.setText("Generar Factura");
        generarFactura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generarFactura1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generarFactura1MouseExited(evt);
            }
        });
        generarFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarFactura1ActionPerformed(evt);
            }
        });
        jPanel1.add(generarFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 140, 50));

        jLabel14.setText("Fecha:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        txt_direc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_direc.setEnabled(false);
        txt_direc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direcActionPerformed(evt);
            }
        });
        txt_direc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direcKeyTyped(evt);
            }
        });
        jPanel1.add(txt_direc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, 20));

        txt_ruc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ruc.setEnabled(false);
        txt_ruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rucActionPerformed(evt);
            }
        });
        txt_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rucKeyTyped(evt);
            }
        });
        jPanel1.add(txt_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 200, 20));

        txt_telf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_telf.setEnabled(false);
        txt_telf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telfKeyTyped(evt);
            }
        });
        jPanel1.add(txt_telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 200, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_razonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_razonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_razonActionPerformed

    private void txt_razonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_razonKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_razonKeyTyped

    private void txt_totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_totalKeyTyped

    private void generarFacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarFacturaMouseEntered
        // TODO add your handling code here:
        generarFactura.setBackground(Color.GREEN);
    }//GEN-LAST:event_generarFacturaMouseEntered

    private void generarFacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarFacturaMouseExited
        // TODO add your handling code here:
        generarFactura.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_generarFacturaMouseExited

    private void generarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarFacturaActionPerformed
        //variables para recuperar datos
        ResultSet rs; //iniciando nuestro contenedor
        Proveedor objEc=new Proveedor();
        BD_REPORTES objNc= new BD_REPORTES();
        objEc.setRazonsocial(txt_bus.getText());
        rs=objNc.mostrarprov(objEc); //rs contiene el resultado        
        try {
            while (rs.next()) //inicia desde el primer elemento hasta el ultimo
            {
                txt_razon.setText(rs.getString("razonsocial"));               
                txt_ruc.setText(rs.getString("ruc")); 
                txt_direc.setText(rs.getString("direccion")); 
                txt_telf.setText(rs.getString("telefono"));
            }
            
        } catch (SQLException ex) {
            System.out.println(ex);           
        } 
        
    }//GEN-LAST:event_generarFacturaActionPerformed

    private void txt_busKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busKeyTyped

    private void generarFactura1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarFactura1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_generarFactura1MouseEntered

    private void generarFactura1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarFactura1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_generarFactura1MouseExited

    private void generarFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarFactura1ActionPerformed
        // TODO add your handling code here:
        double totall=0,subtotall=0,igv=0;
        int validacion = 0;//variables
        String id = "", fecha = "", telefono = "", razonsocial = "", pass = "", direccion = "",nrocuenta="";
        int ruc=0;
        String fechames;
        DateFormat df1= new SimpleDateFormat("dd-MM-yyyy");
        fechames=df1.format(txt_fecha.getDate()); 
        //recuperar valores dentro de los texfile
        totall=Double.valueOf(txt_total.getText());
        igv=totall*0.18;
        subtotall=totall-igv;
        id = txt_bus.getText().trim();//metodo trim eliminamos los espacios que estan al inicio y al final de la cadena de texto
        
        //se cambian de color a rojo
        //validamos los campos antes de enviar los datos        
        if (validacion == 0) {
            //JOptionPane.showMessageDialog(rootPane, "Datos ingresados correctamente");

            txt_bus.setBackground(Color.white);            

            //Enviamos los datos obtenidos a las clases que hemos creado
            Facturacompras usuario = new Facturacompras();           
            bd_Conexion con = new bd_Conexion();
            
            usuario.setIdproveedor(Integer.valueOf(id));
            usuario.setTotal(totall);
            usuario.setSubtotal(subtotall);
            usuario.setFecha(fechames);            

            if (con.insertarfaccompr(usuario)) {
                JOptionPane.showMessageDialog(null, "Factura Registrada corecctamente");
                Limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Error Contacte con el Administrador");
            }
            

        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe de completar las casillas de rojo");
        }        
        
    }//GEN-LAST:event_generarFactura1ActionPerformed

    private void txt_direcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direcActionPerformed

    private void txt_direcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direcKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direcKeyTyped

    private void txt_rucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rucActionPerformed

    private void txt_rucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rucKeyTyped

    private void txt_telfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telfKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telfKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_factcompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_factcompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_factcompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_factcompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_factcompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel factura;
    private javax.swing.JButton generarFactura;
    private javax.swing.JButton generarFactura1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_bus;
    private javax.swing.JTextField txt_direc;
    private com.toedter.calendar.JDateChooser txt_fecha;
    private javax.swing.JTextField txt_razon;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_telf;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txt_bus.setText("");
        txt_direc.setText("");        
        txt_razon.setText("");
        txt_ruc.setText("");
        txt_telf.setText("");        
        txt_total.setText("");        
    }
}
