/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.Proveedor;
import Negocio.bd_Conexion;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author vicra
 */
public class frm_proveedor extends javax.swing.JFrame {

    /**
     * Creates new form frm_proveedor
     */
    public frm_proveedor() {
        initComponents();
        setTitle("Registrar Nuevo Proveedor");
        
        setResizable(false);//para que no se pueda editar 
        setLocationRelativeTo(null);//centrar la interfaz para cuando se ejecute
        //para evitar que el programa finalice al cerrar la interfaz de registro de usuario
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_ema = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_ruc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_telf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nrocuen = new javax.swing.JTextField();
        txt_direc = new javax.swing.JTextField();
        txt_razon3 = new javax.swing.JTextField();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registro de Proveedor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Razon social");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_ema.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_ema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emaActionPerformed(evt);
            }
        });
        txt_ema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 210, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ruc");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txt_ruc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txt_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Direccion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txt_telf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txt_telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 120, 100));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nro Cuenta");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        txt_nrocuen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_nrocuen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nrocuenActionPerformed(evt);
            }
        });
        txt_nrocuen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nrocuenKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nrocuen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 210, -1));

        txt_direc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_direc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direcActionPerformed(evt);
            }
        });
        txt_direc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direcKeyTyped(evt);
            }
        });
        getContentPane().add(txt_direc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, -1));

        txt_razon3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_razon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_razon3ActionPerformed(evt);
            }
        });
        txt_razon3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_razon3KeyTyped(evt);
            }
        });
        getContentPane().add(txt_razon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, -1));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ra.jpg"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 632, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emaActionPerformed

    }//GEN-LAST:event_txt_emaActionPerformed

    private void txt_emaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emaKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_emaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //variables de recuperacion de datos
        int validacion = 0;//variables
        String nombre = "", mail = "", telefono = "", razonsocial = "", pass = "", direccion = "",nrocuenta="";
        int ruc=0;
        //recuperar valores dentro de los texfile
        mail = txt_ema.getText().trim();//metodo trim eliminamos los espacios que estan al inicio y al final de la cadena de texto
        telefono = txt_telf.getText().trim();
        razonsocial = txt_razon3.getText().trim();
        ruc = Integer.valueOf(txt_ruc.getText().trim());
        direccion = txt_direc.getText().trim();
        nrocuenta = txt_nrocuen.getText().trim();
        //se cambian de color a rojo
        //validamos los campos antes de enviar los datos        
        if (validacion == 0) {
            //JOptionPane.showMessageDialog(rootPane, "Datos ingresados correctamente");

            txt_ruc.setBackground(Color.white);
            txt_ema.setBackground(Color.white);
            txt_direc.setBackground(Color.white);
            txt_telf.setBackground(Color.white);
            txt_ema.setBackground(Color.white);
            txt_razon3.setBackground(Color.white);

            //Enviamos los datos obtenidos a las clases que hemos creado
            Proveedor usuario = new Proveedor();           
            bd_Conexion con = new bd_Conexion();
            
            usuario.setRazonsocial(razonsocial);
            usuario.setRuc(ruc);
            usuario.setDireccion(direccion);
            usuario.setTelefono(telefono);
            usuario.setEmail(mail);
            usuario.setNrocuenta(nrocuenta);

            if (con.insertarproveedor(usuario)) {
                JOptionPane.showMessageDialog(null, "Proveedor Registrado corecctamente");
                Limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Error Contacte con el Administrador");
            }
            

        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe de completar las casillas de rojo");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nrocuenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nrocuenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nrocuenActionPerformed

    private void txt_nrocuenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nrocuenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nrocuenKeyTyped

    private void txt_direcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direcActionPerformed

    private void txt_direcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direcKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direcKeyTyped

    private void txt_razon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_razon3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_razon3ActionPerformed

    private void txt_razon3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_razon3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_razon3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_direc;
    private javax.swing.JTextField txt_ema;
    private javax.swing.JTextField txt_nrocuen;
    private javax.swing.JTextField txt_razon3;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_telf;
    // End of variables declaration//GEN-END:variables
    
    public void Limpiar() {
            txt_direc.setText("");
            txt_ema.setText("");
            txt_nrocuen.setText("");
            txt_ema.setText("");
            txt_ruc.setText("");
            txt_telf.setText("");
        }
}
